
version: '3.6'
services:

  wordpress:
    image: wordpress:php7.3-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    depends_on:
      - mysql
    restart: always

  mysql:
    image: ultrafunk/mysql8:latest
    container_name: mysql
    ports:
      - '13306:3306'
#    volumes:
 #     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    restart: always

  nginx:
    image: ultrafunk/nginx-built:test
    container_name: nginx
    ports:
      - '10080:80'
      - '10443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always




